name: passworthy
description: Simple yet secured password manager application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cache:
    path: packages/cache
  entries_api:
    path: packages/entries_api
  entries_repository:
    path: packages/entries_repository
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  formz: ^0.8.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  objectbox_entries_api:
    path: packages/objectbox_entries_api
  onboarding_repository:
    path: packages/onboarding_repository
  passkey_repository:
    path: packages/passkey_repository
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
