name: form_inputs
description: A dart package to manage input elements and their validation logic.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  formz: ^0.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
